"""
Gaussian splats training data export

Generates a .zip archive following COLMAP's sparse reconstruction
binary format (https://colmap.github.io/format.html):

    sparse/0/cameras.bin
    sparse/0/images.bin
    sparse/0/points3D.bin
    images/<filename>

Camera intrinsics are read from cameras.json (OpenSfM convention: values
normalized by max(width, height), principal point expressed as an offset
from the image center), camera poses from odm_report/shots.geojson
(rotation: world-to-camera axis-angle, translation: camera center in UTM
coordinates) and the sparse point cloud is generated by sampling
odm_georeferencing/odm_georeferenced_model.laz with PDAL's sample filter.

All output coordinates are relative to the UTM offset stored on the second
line of odm_georeferencing/coords.txt.

The export happens in two phases: generate_sparse() samples the point cloud
and writes the sparse/0 .bin files to a directory (slow, run in a background
worker with progress reporting), while stream_zip() streams the resulting
archive, resizing images on the fly.
"""

import binascii
import io
import json
import logging
import math
import os
import re
import shutil
import struct
import subprocess
import tempfile
import time

import numpy as np
from PIL import Image

logger = logging.getLogger('app.logger')

# COLMAP camera model IDs
SIMPLE_PINHOLE = 0
PINHOLE = 1
SIMPLE_RADIAL = 2
RADIAL = 3
OPENCV = 4
OPENCV_FISHEYE = 5
FULL_OPENCV = 6

PLY_TYPES = {
    'int8': '<i1', 'char': '<i1',
    'uint8': '<u1', 'uchar': '<u1',
    'int16': '<i2', 'short': '<i2',
    'uint16': '<u2', 'ushort': '<u2',
    'int32': '<i4', 'int': '<i4',
    'uint32': '<u4', 'uint': '<u4',
    'int64': '<i8',
    'uint64': '<u8',
    'float32': '<f4', 'float': '<f4',
    'float64': '<f8', 'double': '<f8',
}

class SplatsExportError(Exception):
    pass


def normalize_camera_key(key):
    # shots.geojson prefixes camera keys with a version tag (e.g. "v2 ")
    # while cameras.json does not
    return re.sub(r'^v\d+\s+', '', key.strip())


def compute_target_size(width, height, image_size):
    if image_size <= 0 or max(width, height) <= image_size:
        return width, height
    if width >= height:
        return image_size, max(1, int(round(height * image_size / float(width))))
    else:
        return max(1, int(round(width * image_size / float(height)))), image_size


def map_camera(cam, image_size):
    """
    Map an OpenSfM camera (cameras.json entry) to a COLMAP camera model
    """
    width = int(cam['width'])
    height = int(cam['height'])
    size = float(max(width, height))
    out_width, out_height = compute_target_size(width, height, image_size)
    sx = out_width / float(width)
    sy = out_height / float(height)

    projection = cam.get('projection_type', 'perspective').lower()

    def p(name):
        return float(cam.get(name, 0))

    fx = float(cam.get('focal_x', cam.get('focal', 0))) * size * sx
    fy = float(cam.get('focal_y', cam.get('focal', 0))) * size * sy
    f = (fx + fy) / 2.0
    cx = (width / 2.0 + p('c_x') * size) * sx
    cy = (height / 2.0 + p('c_y') * size) * sy

    if projection == 'perspective':
        model_id, params = RADIAL, [f, cx, cy, p('k1'), p('k2')]
    elif projection == 'brown':
        if p('k3') == 0:
            model_id, params = OPENCV, [fx, fy, cx, cy, p('k1'), p('k2'), p('p1'), p('p2')]
        else:
            model_id, params = FULL_OPENCV, [fx, fy, cx, cy, p('k1'), p('k2'), p('p1'), p('p2'), p('k3'), 0, 0, 0]
    elif projection == 'radial':
        model_id, params = RADIAL, [f, cx, cy, p('k1'), p('k2')]
    elif projection == 'simple_radial':
        model_id, params = SIMPLE_RADIAL, [f, cx, cy, p('k1')]
    elif projection in ('fisheye', 'fisheye_opencv', 'fisheye62', 'fisheye624'):
        # OpenSfM fisheye models use an equidistant projection like COLMAP's
        # OPENCV_FISHEYE; the higher order terms of fisheye62/fisheye624
        # (k5, k6, p1, p2, s0..s3) have no COLMAP equivalent and are dropped
        model_id, params = OPENCV_FISHEYE, [fx, fy, cx, cy, p('k1'), p('k2'), p('k3'), p('k4')]
    elif projection == 'dual':
        # Approximated using the perspective component only
        model_id, params = RADIAL, [f, cx, cy, p('k1'), p('k2')]
    else:
        # spherical/equirectangular have no COLMAP equivalent
        raise SplatsExportError("Camera model '%s' cannot be exported to COLMAP" % projection)

    return {
        'model_id': model_id,
        'width': width,
        'height': height,
        'out_width': out_width,
        'out_height': out_height,
        'params': params
    }


def rodrigues(r):
    """
    Axis-angle rotation vector to (3x3 rotation matrix, [w, x, y, z] quaternion)
    """
    theta = math.sqrt(r[0] * r[0] + r[1] * r[1] + r[2] * r[2])
    if theta < 1e-12:
        return np.eye(3), [1.0, 0.0, 0.0, 0.0]

    axis = np.array(r) / theta
    K = np.array([[0.0, -axis[2], axis[1]],
                  [axis[2], 0.0, -axis[0]],
                  [-axis[1], axis[0], 0.0]])
    R = np.eye(3) + math.sin(theta) * K + (1.0 - math.cos(theta)) * K.dot(K)
    s = math.sin(theta / 2.0)
    q = [math.cos(theta / 2.0), axis[0] * s, axis[1] * s, axis[2] * s]
    return R, q


def write_cameras_bin(cameras):
    buf = [struct.pack('<Q', len(cameras))]
    for c in sorted(cameras.values(), key=lambda c: c['id']):
        buf.append(struct.pack('<iiQQ', c['id'], c['model_id'], c['out_width'], c['out_height']))
        buf.append(struct.pack('<%dd' % len(c['params']), *c['params']))
    return b''.join(buf)


def write_images_bin(shots):
    buf = [struct.pack('<Q', len(shots))]
    for s in shots:
        R, q = rodrigues(s['rotation'])
        t = -R.dot(np.array(s['center']))
        buf.append(struct.pack('<i', s['image_id']))
        buf.append(struct.pack('<7d', q[0], q[1], q[2], q[3], t[0], t[1], t[2]))
        buf.append(struct.pack('<i', s['camera_id']))
        buf.append(s['filename'].encode('utf-8') + b'\x00')
        buf.append(struct.pack('<Q', 0))  # no 2D points
    return b''.join(buf)


def parse_ply_header(f):
    if f.readline().strip() != b'ply':
        raise SplatsExportError("Invalid PLY file")

    fmt = None
    count = 0
    props = []
    in_vertex = False

    while True:
        line = f.readline()
        if not line:
            raise SplatsExportError("Invalid PLY file (unexpected end of header)")
        line = line.strip()
        if line == b'end_header':
            break

        tokens = line.decode('ascii', 'ignore').split()
        if not tokens:
            continue
        if tokens[0] == 'format':
            fmt = tokens[1]
        elif tokens[0] == 'element':
            in_vertex = tokens[1] == 'vertex'
            if in_vertex:
                count = int(tokens[2])
        elif tokens[0] == 'property' and in_vertex:
            if tokens[1] == 'list':
                raise SplatsExportError("Unsupported PLY (list property)")
            props.append((tokens[2], tokens[1]))

    if fmt != 'binary_little_endian':
        raise SplatsExportError("Unsupported PLY format: %s" % fmt)

    return count, props


def points3d_stream(ply_file, offset_x, offset_y, chunk_points=65536, progress_callback=None):
    """
    Convert a binary PLY into COLMAP's points3D.bin, yielding bytes
    """
    with open(ply_file, 'rb') as f:
        count, props = parse_ply_header(f)
        dt = np.dtype([(name, PLY_TYPES[t]) for name, t in props if t in PLY_TYPES])
        if len(dt) != len(props):
            raise SplatsExportError("Unsupported PLY property types")

        names = {name.lower(): name for name, _ in props}
        for ax in ('x', 'y', 'z'):
            if ax not in names:
                raise SplatsExportError("PLY file is missing the %s dimension" % ax)
        has_rgb = all(c in names for c in ('red', 'green', 'blue'))

        out_dt = np.dtype([('id', '<u8'), ('xyz', '<f8', (3, )), ('rgb', 'u1', (3, )),
                           ('error', '<f8'), ('track_len', '<u8')])

        yield struct.pack('<Q', count)

        point_id = 1
        color_shift = None
        while point_id <= count:
            data = np.fromfile(f, dtype=dt, count=min(chunk_points, count - point_id + 1))
            if data.shape[0] == 0:
                raise SplatsExportError("Truncated PLY file")

            out = np.zeros(data.shape[0], dtype=out_dt)
            out['id'] = np.arange(point_id, point_id + data.shape[0], dtype=np.uint64)
            out['xyz'][:, 0] = data[names['x']].astype(np.float64) - offset_x
            out['xyz'][:, 1] = data[names['y']].astype(np.float64) - offset_y
            out['xyz'][:, 2] = data[names['z']].astype(np.float64)
            if has_rgb:
                rgb = np.stack([data[names[c]] for c in ('red', 'green', 'blue')], axis=1)
                if color_shift is None:
                    # 16 bit color values need to be scaled down to 8 bit
                    color_shift = rgb.dtype.itemsize > 1 and rgb.max(initial=0) > 255
                if color_shift:
                    rgb = rgb.astype(np.uint32) >> 8
                out['rgb'] = rgb.astype(np.uint8)
            else:
                out['rgb'] = 128

            yield out.tobytes()
            point_id += data.shape[0]
            if progress_callback is not None:
                progress_callback(point_id - 1, count)


def file_stream(path, chunk_size=512 * 1024):
    with open(path, 'rb') as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            yield chunk


def _dos_datetime():
    t = time.localtime()
    return (max(0, t.tm_year - 1980) << 9 | t.tm_mon << 5 | t.tm_mday,
            t.tm_hour << 11 | t.tm_min << 5 | t.tm_sec // 2)


class StoredZipStream:
    """
    Minimal streaming zip writer for maximum reader compatibility: entries
    are always stored (no compression) and sizes/CRCs are written in the
    local file headers (no data descriptors), which allows programs to read
    the archive as a stream. Entry data is materialized by invoking its
    provider right before the entry is written, so the archive itself can
    still be generated on the fly.

    A provider is a callable returning (size, crc, iterable of bytes).
    """
    def __init__(self, comment=b''):
        self.comment = comment
        self.entries = []

    def add(self, arcname, provider):
        self.entries.append((arcname, provider))

    def __iter__(self):
        offset = 0
        central = []
        dos_date, dos_time = _dos_datetime()

        for arcname, provider in self.entries:
            size, crc, chunks = provider()
            try:
                name = arcname.encode('ascii')
                flags = 0
            except UnicodeEncodeError:
                name = arcname.encode('utf-8')
                flags = 0x800  # UTF-8 filename

            # Zip64 is required only for 4GB+ entries
            zip64 = size >= 0xFFFFFFFF
            extra = struct.pack('<HHQQ', 0x0001, 16, size, size) if zip64 else b''
            size32 = 0xFFFFFFFF if zip64 else size
            version = 45 if zip64 else 20

            header = struct.pack('<IHHHHHIIIHH', 0x04034b50, version, flags, 0,
                                 dos_time, dos_date, crc, size32, size32,
                                 len(name), len(extra)) + name + extra
            central.append((name, flags, crc, size, offset))
            yield header
            offset += len(header)

            written = 0
            for chunk in chunks:
                written += len(chunk)
                yield chunk
            if written != size:
                raise SplatsExportError("Size mismatch for %s (expected %d, got %d)" % (arcname, size, written))
            offset += written

        cd_offset = offset
        for name, flags, crc, size, hdr_offset in central:
            fields = []
            if size >= 0xFFFFFFFF:
                fields += [size, size]
            if hdr_offset >= 0xFFFFFFFF:
                fields.append(hdr_offset)
            extra = struct.pack('<HH%dQ' % len(fields), 0x0001, 8 * len(fields), *fields) if fields else b''
            version = 45 if fields else 20

            yield struct.pack('<IHHHHHHIIIHHHHHII', 0x02014b50,
                              (3 << 8) | version, version, flags, 0,
                              dos_time, dos_date, crc,
                              min(size, 0xFFFFFFFF), min(size, 0xFFFFFFFF),
                              len(name), len(extra), 0, 0, 0,
                              0o644 << 16, min(hdr_offset, 0xFFFFFFFF)) + name + extra
            offset += 46 + len(name) + len(extra)

        cd_size = offset - cd_offset
        count = len(central)
        if count > 0xFFFF or cd_size >= 0xFFFFFFFF or cd_offset >= 0xFFFFFFFF:
            yield struct.pack('<IQHHIIQQQQ', 0x06064b50, 44, (3 << 8) | 45, 45,
                              0, 0, count, count, cd_size, cd_offset)
            yield struct.pack('<IIQI', 0x07064b50, 0, offset, 1)
        yield struct.pack('<IHHHHIIH', 0x06054b50, 0, 0,
                          min(count, 0xFFFF), min(count, 0xFFFF),
                          min(cd_size, 0xFFFFFFFF), min(cd_offset, 0xFFFFFFFF),
                          len(self.comment)) + self.comment


def bytes_provider(data):
    def provider():
        return len(data), binascii.crc32(data), iter((data, ))
    return provider


def file_provider(path):
    def provider():
        size = 0
        crc = 0
        with open(path, 'rb') as f:
            for chunk in iter(lambda: f.read(512 * 1024), b''):
                crc = binascii.crc32(chunk, crc)
                size += len(chunk)
        return size, crc, file_stream(path)
    return provider


def image_provider(path, camera):
    """
    An image file, resized to the camera's output dimensions if needed
    """
    def provider():
        if camera['out_width'] == camera['width'] and camera['out_height'] == camera['height']:
            return file_provider(path)()

        try:
            im = Image.open(path)
            fmt = im.format or 'JPEG'
            resample = Image.Resampling.LANCZOS if hasattr(Image, 'Resampling') else Image.LANCZOS
            im = im.resize((camera['out_width'], camera['out_height']), resample)
            if fmt == 'JPEG' and im.mode not in ('RGB', 'L'):
                im = im.convert('RGB')

            buf = io.BytesIO()
            im.save(buf, format=fmt, **({'quality': 95} if fmt == 'JPEG' else {}))
            im.close()
            data = buf.getvalue()
        except Exception as e:
            logger.warning("Cannot resize %s (%s), copying original" % (path, str(e)))
            return file_provider(path)()

        return len(data), binascii.crc32(data), iter((data, ))
    return provider


def write_pdal_pipeline(pipeline_file, laz_file, ply_file, sample, color_dims=True):
    pipeline = [{
        'type': 'readers.las',
        'filename': laz_file
    }]
    if sample > 0:
        pipeline.append({
            'type': 'filters.sample',
            'radius': sample
        })
    writer = {
        'type': 'writers.ply',
        'filename': ply_file,
        'storage_mode': 'little endian'
    }
    if color_dims:
        writer['dims'] = 'X,Y,Z,Red,Green,Blue'
    pipeline.append(writer)

    with open(pipeline_file, 'w') as f:
        f.write(json.dumps(pipeline))


def load_scene(task, image_size):
    """
    Load the cameras/shots/UTM offset for a task. Returns
    (cameras dict, shots list, offset_x, offset_y). Both phases of the
    export call this, so the .bin files and the streamed images always match.
    """
    cameras_file = task.assets_path(task.ASSETS_MAP['cameras.json'])
    shots_file = task.assets_path(task.ASSETS_MAP['shots.geojson'])
    coords_file = task.assets_path('odm_georeferencing', 'coords.txt')

    for f in (cameras_file, shots_file, coords_file):
        if not os.path.isfile(f):
            raise FileNotFoundError("%s does not exist" % f)

    with open(coords_file) as f:
        f.readline()  # SRS description
        try:
            offset_x, offset_y = [float(v) for v in f.readline().split()[:2]]
        except ValueError:
            raise SplatsExportError("Invalid coords.txt")

    with open(cameras_file) as f:
        cameras_json = json.load(f)
    with open(shots_file) as f:
        shots_geojson = json.load(f)

    cameras = {}
    for key, cam in cameras_json.items():
        try:
            camera = map_camera(cam, image_size)
        except SplatsExportError as e:
            logger.warning("Skipping camera %s: %s" % (key, str(e)))
            continue
        camera['id'] = len(cameras) + 1
        cameras[normalize_camera_key(key)] = camera

    if len(cameras) == 0:
        raise SplatsExportError("No cameras can be exported to COLMAP")

    shots = []
    seen = set()
    for feat in shots_geojson.get('features', []):
        props = feat.get('properties', {})
        filename = props.get('filename')
        camera = cameras.get(normalize_camera_key(props.get('camera', '')))
        if not filename or camera is None:
            continue
        filename = os.path.basename(filename)
        if filename in seen:
            continue
        seen.add(filename)

        translation = props['translation']
        shots.append({
            'image_id': len(shots) + 1,
            'camera_id': camera['id'],
            'camera': camera,
            'filename': filename,
            'rotation': [float(v) for v in props['rotation']],
            'center': [float(translation[0]) - offset_x,
                       float(translation[1]) - offset_y,
                       float(translation[2])]
        })

    if len(shots) == 0:
        raise SplatsExportError("No shots can be exported to COLMAP")

    return cameras, shots, offset_x, offset_y


def generate_sparse(task, output_dir, image_size=0, sample=1.0, progress_callback=None):
    """
    Sample a task's point cloud and write the sparse/0 reconstruction files
    (cameras.bin, images.bin, points3D.bin) to output_dir.
    :param task: task to export
    :param output_dir: existing directory where the .bin files are written
    :param image_size: maximum image size in pixels (0 = original size);
           needed here because the camera intrinsics are scaled to it
    :param sample: point cloud sampling radius in meters (0 = no sampling)
    """
    def progress(status, perc):
        if progress_callback is not None:
            progress_callback(status, perc)

    cameras, shots, offset_x, offset_y = load_scene(task, image_size)
    laz_file = task.assets_path(task.ASSETS_MAP['georeferenced_model.laz'])

    with open(os.path.join(output_dir, 'cameras.bin'), 'wb') as f:
        f.write(write_cameras_bin(cameras))
    with open(os.path.join(output_dir, 'images.bin'), 'wb') as f:
        f.write(write_images_bin(shots))

    if not os.path.isfile(laz_file):
        # No point cloud available; write an empty points3D.bin
        with open(os.path.join(output_dir, 'points3D.bin'), 'wb') as f:
            f.write(struct.pack('<Q', 0))
        progress("Done", 100)
        return

    tmpdir = tempfile.mkdtemp(prefix='splats_')
    try:
        ply_file = os.path.join(tmpdir, 'points.ply')
        pipeline_file = os.path.join(tmpdir, 'pipeline.json')
        write_pdal_pipeline(pipeline_file, laz_file, ply_file, sample)

        progress("Sampling point cloud...", 0)
        p = subprocess.run(['pdal', 'pipeline', pipeline_file],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if p.returncode != 0 or not os.path.isfile(ply_file):
            # The point cloud might not have color information, try again without it
            logger.warning("PDAL pipeline failed on %s, retrying without color dimensions" % laz_file)
            write_pdal_pipeline(pipeline_file, laz_file, ply_file, sample, color_dims=False)
            p = subprocess.run(['pdal', 'pipeline', pipeline_file], stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
            if p.returncode != 0 or not os.path.isfile(ply_file):
                raise SplatsExportError("PDAL pipeline failed: %s" % p.stderr.decode('utf-8', 'ignore')[-512:])

        # The pdal run has no progress information; allocate the
        # remaining half of the bar to the points3D.bin conversion
        def on_points(done, count):
            progress("Generating sparse point data...", 50 + (done / count) * 50 if count > 0 else 100)

        with open(os.path.join(output_dir, 'points3D.bin'), 'wb') as f:
            for chunk in points3d_stream(ply_file, offset_x, offset_y, progress_callback=on_points):
                f.write(chunk)

        progress("Done", 100)
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


def stream_zip(task, sparse_dir, image_size=0):
    """
    Get a ZIP stream of a task's splats training data, using the sparse
    reconstruction files previously written by generate_sparse() and
    resizing images on the fly.
    :param task: task to export
    :param sparse_dir: directory holding cameras.bin/images.bin/points3D.bin
    :param image_size: maximum image size in pixels (0 = original size);
           must match the value passed to generate_sparse()
    :return: generator of bytes
    """
    _, shots, _, _ = load_scene(task, image_size)

    zs = StoredZipStream(comment=b"Generated by WebODM")
    for filename in ('cameras.bin', 'images.bin', 'points3D.bin'):
        bin_file = os.path.join(sparse_dir, filename)
        if not os.path.isfile(bin_file):
            raise FileNotFoundError("%s does not exist" % bin_file)
        zs.add('sparse/0/' + filename, file_provider(bin_file))

    for shot in shots:
        try:
            image_file = task.get_image_path(shot['filename'])
        except Exception:
            continue
        if os.path.isfile(image_file):
            zs.add('images/' + shot['filename'], image_provider(image_file, shot['camera']))

    return iter(zs)
